apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster

metadata:
  name: worker-argo-1
  namespace: tanzu-19-ns

spec:
  distribution:
    version: v1.22.9

  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: tanzu-storage

    nodePools:
    - name: workerpool-1
      replicas: 2
      vmClass: worker-8-16
      storageClass: tanzu-storage

  settings:
    storage:
      defaultClass: tanzu-storage
      classes:
        - tanzu-storage
        - tanzu-arch
